extends:
  - plugin:markdown/recommended
env:
  es6: true
parserOptions:
  sourceType: "module"
plugins:
  - markdown
overrides:
  - files: '**/*.md'
    processor: 'markdown/markdown'
rules:
  eol-last: error
  indent: ["error", 2, { "SwitchCase": 1 }]
  no-trailing-spaces: error
